package com.qw.wefly.core.modules.tencent.model.request;

import com.alibaba.fastjson.annotation.JSONField;
import com.qw.wefly.core.modules.tencent.model.inner.TencentFiltering;
import lombok.Data;

import java.util.List;

@Data
public class TencentDailyReportInfo {

    @JSONField(name = "date")
    private String date;
    @JSONField(name = "view_count")
    private Integer viewCount;
    @JSONField(name = "download_count")
    private Integer downloadCount;
    @JSONField(name = "activated_count")
    private Integer activatedCount;
    @JSONField(name = "activated_rate")
    private BigDecimal activatedRate;
    @JSONField(name = "thousand_display_price")
    private Integer thousandDisplayPrice;
    @JSONField(name = "valid_click_count")
    private Integer validClickCount;
    @JSONField(name = "ctr")
    private BigDecimal ctr;
    @JSONField(name = "cpc")
    private Integer cpc;
    @JSONField(name = "cost")
    private Integer cost;
    @JSONField(name = "key_page_view_cost")
    private Integer keyPageViewCost;
    @JSONField(name = "platform_page_view_count")
    private Integer platformPageViewCount;
    @JSONField(name = "platform_page_view_rate")
    private BigDecimal platformPageViewRate;
    @JSONField(name = "own_page_navigation_count")
    private Integer ownPageNavigationCount;
    @JSONField(name = "own_page_navi_cost")
    private Integer ownPageNaviCost;
    @JSONField(name = "platform_page_navigation_count")
    private Integer platformPageNavigationCount;
    @JSONField(name = "platform_page_navigation_cost")
    private Integer platformPageNavigationCost;
    @JSONField(name = "platform_shop_navigation_count")
    private Integer platformShopNavigationCount;
    @JSONField(name = "platform_shop_navigation_cost")
    private Integer platformShopNavigationCost;
    @JSONField(name = "add_to_cart_price")
    private Integer addToCartPrice;
    @JSONField(name = "own_page_coupon_get_count")
    private Integer ownPageCouponGetCount;
    @JSONField(name = "own_page_coupon_get_cost")
    private Integer ownPageCouponGetCost;
    @JSONField(name = "platform_coupon_get_count")
    private Integer platformCouponGetCount;
    @JSONField(name = "platform_coupon_get_cost")
    private Integer platformCouponGetCost;
    @JSONField(name = "app_order_rate")
    private BigDecimal appOrderRate;
    @JSONField(name = "order_amount")
    private Integer orderAmount;
    @JSONField(name = "order_unit_price")
    private Integer orderUnitPrice;
    @JSONField(name = "order_roi")
    private BigDecimal orderRoi;
    @JSONField(name = "deliver_count")
    private Integer deliverCount;
    @JSONField(name = "deliver_cost")
    private Integer deliverCost;
    @JSONField(name = "sign_in_count")
    private Integer signInCount;
    @JSONField(name = "sign_in_cost")
    private Integer signInCost;
    @JSONField(name = "download_rate")
    private BigDecimal downloadRate;
    @JSONField(name = "download_cost")
    private Integer downloadCost;
    @JSONField(name = "install_count")
    private Integer installCount;
    @JSONField(name = "install_cost")
    private Integer installCost;
    @JSONField(name = "click_activated_rate")
    private BigDecimal clickActivatedRate;
    @JSONField(name = "activated_cost")
    private Integer activatedCost;
    @JSONField(name = "retention_count")
    private Integer retentionCount;
    @JSONField(name = "retention_rate")
    private BigDecimal retentionRate;
    @JSONField(name = "retention_cost")
    private Integer retentionCost;
    @JSONField(name = "key_page_view_count")
    private Integer keyPageViewCount;
    @JSONField(name = "app_register_count")
    private Integer appRegisterCount;
    @JSONField(name = "app_register_cost")
    private Integer appRegisterCost;
    @JSONField(name = "app_application_count")
    private Integer appApplicationCount;
    @JSONField(name = "app_application_cost")
    private Integer appApplicationCost;
    @JSONField(name = "app_add_to_cart_count")
    private Integer appAddToCartCount;
    @JSONField(name = "add_to_cart_amount")
    private Integer addToCartAmount;
    @JSONField(name = "app_add_to_cart_cost")
    private Integer appAddToCartCost;
    @JSONField(name = "app_order_count")
    private Integer appOrderCount;
    @JSONField(name = "app_order_cost")
    private Integer appOrderCost;
    @JSONField(name = "app_checkout_count")
    private Integer appCheckoutCount;
    @JSONField(name = "app_checkout_amount")
    private Integer appCheckoutAmount;
    @JSONField(name = "app_checkout_cost")
    private Integer appCheckoutCost;
    @JSONField(name = "platform_coupon_click_count")
    private Integer platformCouponClickCount;
    @JSONField(name = "platform_coupon_get_rate")
    private BigDecimal platformCouponGetRate;
    @JSONField(name = "follow_count")
    private Integer followCount;
    @JSONField(name = "follow_cost")
    private Integer followCost;
    @JSONField(name = "forward_count")
    private Integer forwardCount;
    @JSONField(name = "forward_cost")
    private Integer forwardCost;
    @JSONField(name = "read_count")
    private Integer readCount;
    @JSONField(name = "read_cost")
    private Integer readCost;
    @JSONField(name = "praise_count")
    private Integer praiseCount;
    @JSONField(name = "praise_cost")
    private Integer praiseCost;
    @JSONField(name = "comment_count")
    private Integer commentCount;
    @JSONField(name = "comment_cost")
    private Integer commentCost;
    @JSONField(name = "ad_pur_val_app")
    private Integer adPurValApp;
    @JSONField(name = "game_create_role_count")
    private Integer gameCreateRoleCount;
    @JSONField(name = "game_authorize_count")
    private Integer gameAuthorizeCount;
    @JSONField(name = "game_tutorial_finish_count")
    private Integer gameTutorialFinishCount;
    @JSONField(name = "effective_leads_count")
    private Integer effectiveLeadsCount;
    @JSONField(name = "effective_cost")
    private Integer effectiveCost;
    @JSONField(name = "effective_consult_count")
    private Integer effectiveConsultCount;
    @JSONField(name = "potential_consult_count")
    private Integer potentialConsultCount;
    @JSONField(name = "app_checkout_rate")
    private BigDecimal appCheckoutRate;
    @JSONField(name = "app_activated_checkout_rate")
    private BigDecimal appActivatedCheckoutRate;
    @JSONField(name = "app_register_rate")
    private BigDecimal appRegisterRate;
    @JSONField(name = "deliver_rate")
    private BigDecimal deliverRate;
    @JSONField(name = "install_rate")
    private BigDecimal installRate;
    @JSONField(name = "arppu_cost")
    private Integer arppuCost;
    @JSONField(name = "arpu_cost")
    private Integer arpuCost;
    @JSONField(name = "app_ad_pur_arpu_cost")
    private Integer appAdPurArpuCost;
    @JSONField(name = "cheout_fd")
    private Integer cheoutFd;
    @JSONField(name = "cheout_td")
    private Integer cheoutTd;
    @JSONField(name = "cheout_ow")
    private Integer cheoutOw;
    @JSONField(name = "cheout_tw")
    private Integer cheoutTw;
    @JSONField(name = "cheout_om")
    private Integer cheoutOm;
    @JSONField(name = "cheout_fd_reward")
    private BigDecimal cheoutFdReward;
    @JSONField(name = "cheout_td_reward")
    private BigDecimal cheoutTdReward;
    @JSONField(name = "cheout_ow_reward")
    private BigDecimal cheoutOwReward;
    @JSONField(name = "cheout_tw_reward")
    private BigDecimal cheoutTwReward;
    @JSONField(name = "cheout_om_reward")
    private BigDecimal cheoutOmReward;
    @JSONField(name = "cheout_total_reward")
    private BigDecimal cheoutTotalReward;
    @JSONField(name = "first_pay_count")
    private Integer firstPayCount;
    @JSONField(name = "first_pay_rate")
    private BigDecimal firstPayRate;
    @JSONField(name = "pre_cre_app")
    private Integer preCreApp;
    @JSONField(name = "pre_cre_app_val")
    private Integer preCreAppVal;
    @JSONField(name = "cre_app")
    private Integer creApp;
    @JSONField(name = "cre_app_val")
    private Integer creAppVal;
    @JSONField(name = "withdr_dep_app")
    private Integer withdrDepApp;
    @JSONField(name = "withdr_dep_app_val")
    private Integer withdrDepAppVal;
    @JSONField(name = "first_pay_cost")
    private Integer firstPayCost;
    @JSONField(name = "landing_page_click_count")
    private Integer landingPageClickCount;
    @JSONField(name = "scan_follow_count")
    private Integer scanFollowCount;
    @JSONField(name = "app_order_amount")
    private Integer appOrderAmount;
    @JSONField(name = "tool_consult_count")
    private Integer toolConsultCount;
    @JSONField(name = "lottery_leads_count")
    private Integer lotteryLeadsCount;
    @JSONField(name = "lottery_leads_cost")
    private Integer lotteryLeadsCost;
    @JSONField(name = "conversions_count")
    private Integer conversionsCount;
    @JSONField(name = "conversions_rate")
    private BigDecimal conversionsRate;
    @JSONField(name = "conversions_cost")
    private Integer conversionsCost;
    @JSONField(name = "deep_conversions_count")
    private Integer deepConversionsCount;
    @JSONField(name = "deep_conversions_rate")
    private BigDecimal deepConversionsRate;
    @JSONField(name = "deep_conversions_cost")
    private Integer deepConversionsCost;
    @JSONField(name = "first_memcard_app_count")
    private Integer firstMemcardAppCount;
    @JSONField(name = "memcard_app_count")
    private Integer memcardAppCount;
    @JSONField(name = "first_memcard_app_rate")
    private BigDecimal firstMemcardAppRate;
    @JSONField(name = "first_memcard_app_cost")
    private Integer firstMemcardAppCost;
    @JSONField(name = "valuable_click_count")
    private Integer valuableClickCount;
    @JSONField(name = "valuable_click_rate")
    private BigDecimal valuableClickRate;
    @JSONField(name = "valuable_click_cost")
    private Integer valuableClickCost;
    @JSONField(name = "video_play_count")
    private Integer videoPlayCount;
    @JSONField(name = "click_image_count")
    private Integer clickImageCount;
    @JSONField(name = "click_detail_count")
    private Integer clickDetailCount;
    @JSONField(name = "click_head_count")
    private Integer clickHeadCount;
    @JSONField(name = "click_nick_count")
    private Integer clickNickCount;
    @JSONField(name = "click_poi_count")
    private Integer clickPoiCount;
    @JSONField(name = "video_inner_play_count")
    private Integer videoInnerPlayCount;
    @JSONField(name = "cpn_click_button_count")
    private Integer cpnClickButtonCount;
    @JSONField(name = "cpn_click_button_uv")
    private Integer cpnClickButtonUv;
    @JSONField(name = "key_page_uv")
    private Integer keyPageUv;
    @JSONField(name = "special_page_exp_uv")
    private Integer specialPageExpUv;
    @JSONField(name = "special_page_exp_cost")
    private Integer specialPageExpCost;
    @JSONField(name = "app_apply_uv")
    private Integer appApplyUv;
    @JSONField(name = "app_pre_credit_uv")
    private Integer appPreCreditUv;
    @JSONField(name = "app_credit_uv")
    private Integer appCreditUv;
    @JSONField(name = "app_withdraw_uv")
    private Integer appWithdrawUv;
    @JSONField(name = "wechat_app_register_uv")
    private Integer wechatAppRegisterUv;
    @JSONField(name = "no_interest_count")
    private Integer noInterestCount;
    @JSONField(name = "first_day_order_count")
    private Integer firstDayOrderCount;
    @JSONField(name = "first_day_order_amount")
    private Integer firstDayOrderAmount;
    @JSONField(name = "add_wishlist_count")
    private Integer addWishlistCount;
    @JSONField(name = "video_outer_play_count")
    private Integer videoOuterPlayCount;
    @JSONField(name = "campaign_id")
    private Integer campaignId;
    @JSONField(name = "adgroup_id")
    private Integer adgroupId;
    @JSONField(name = "ad_id")
    private Integer adId;
    @JSONField(name = "promoted_object_type")
    private Enum promotedObjectType;
    @JSONField(name = "promoted_object_id")
    private String promotedObjectId;
    @JSONField(name = "union_position_id")
    private Integer unionPositionId;
    @JSONField(name = "template_id")
    private Integer templateId;
    @JSONField(name = "add_to_cart_cost")
    private Integer addToCartCost;
    @JSONField(name = "app_add_to_cart_rate")
    private BigDecimal appAddToCartRate;
    @JSONField(name = "deep_link_cnt")
    private Integer deepLinkCnt;
    @JSONField(name = "app_application_rate")
    private BigDecimal appApplicationRate;
    @JSONField(name = "app_aroused_rate")
    private BigDecimal appArousedRate;
    @JSONField(name = "app_aroused_cost")
    private Integer appArousedCost;
    @JSONField(name = "is_expand_targeting")
    private Boolean isExpandTargeting;
    @JSONField(name = "wechat_account_id")
    private String wechatAccountId;
    @JSONField(name = "wechat_agency_id")
    private String wechatAgencyId;
    @JSONField(name = "cost_deviation_rate")
    private BigDecimal costDeviationRate;
    @JSONField(name = "compensation_amount")
    private Integer compensationAmount;
    @JSONField(name = "view_user_count")
    private Integer viewUserCount;
    @JSONField(name = "avg_view_per_user")
    private BigDecimal avgViewPerUser;
    @JSONField(name = "click_user_count")
    private Integer clickUserCount;
    @JSONField(name = "image_click_user_count")
    private Integer imageClickUserCount;
    @JSONField(name = "video_click_user_count")
    private Integer videoClickUserCount;
    @JSONField(name = "link_click_user_count")
    private Integer linkClickUserCount;
    @JSONField(name = "portrait_click_user_count")
    private Integer portraitClickUserCount;
    @JSONField(name = "nickname_click_user_count")
    private Integer nicknameClickUserCount;
    @JSONField(name = "poi_click_user_count")
    private Integer poiClickUserCount;
    @JSONField(name = "platform_key_page_view_user_count")
    private Integer platformKeyPageViewUserCount;
    @JSONField(name = "platform_key_page_avg_view_per_user")
    private BigDecimal platformKeyPageAvgViewPerUser;
    @JSONField(name = "platform_key_page_view_duration")
    private BigDecimal platformKeyPageViewDuration;
    @JSONField(name = "cpn_click_button_cost")
    private Integer cpnClickButtonCost;
    @JSONField(name = "praise_user_count")
    private Integer praiseUserCount;
    @JSONField(name = "comment_user_count")
    private Integer commentUserCount;
    @JSONField(name = "order_count")
    private Integer orderCount;
    @JSONField(name = "order_rate")
    private BigDecimal orderRate;
    @JSONField(name = "page_consult_user_count")
    private Integer pageConsultUserCount;
    @JSONField(name = "valid_page_consult_user_count")
    private Integer validPageConsultUserCount;
    @JSONField(name = "wechat_minigame_register_cost")
    private Integer wechatMinigameRegisterCost;
    @JSONField(name = "wechat_minigame_register_rate")
    private BigDecimal wechatMinigameRegisterRate;
    @JSONField(name = "wechat_minigame_arpu")
    private BigDecimal wechatMinigameArpu;
    @JSONField(name = "wechat_minigame_retention_count")
    private Integer wechatMinigameRetentionCount;
    @JSONField(name = "wechat_minigame_checkout_count")
    private Integer wechatMinigameCheckoutCount;
    @JSONField(name = "wechat_minigame_checkout_amount")
    private Integer wechatMinigameCheckoutAmount;
    @JSONField(name = "official_account_follow_count")
    private Integer officialAccountFollowCount;
    @JSONField(name = "official_account_follow_cost")
    private Integer officialAccountFollowCost;
    @JSONField(name = "official_account_follow_rate")
    private BigDecimal officialAccountFollowRate;
    @JSONField(name = "official_account_register_user_count")
    private Integer officialAccountRegisterUserCount;
    @JSONField(name = "official_account_register_rate")
    private BigDecimal officialAccountRegisterRate;
    @JSONField(name = "official_account_register_cost")
    private Integer officialAccountRegisterCost;
    @JSONField(name = "official_account_register_amount")
    private Integer officialAccountRegisterAmount;
    @JSONField(name = "official_account_register_roi")
    private Integer officialAccountRegisterRoi;
    @JSONField(name = "official_account_apply_count")
    private Integer officialAccountApplyCount;
    @JSONField(name = "official_account_apply_user_count")
    private Integer officialAccountApplyUserCount;
    @JSONField(name = "official_account_apply_rate")
    private BigDecimal officialAccountApplyRate;
    @JSONField(name = "official_account_apply_cost")
    private Integer officialAccountApplyCost;
    @JSONField(name = "official_account_apply_amount")
    private Integer officialAccountApplyAmount;
    @JSONField(name = "official_account_apply_roi")
    private Integer officialAccountApplyRoi;
    @JSONField(name = "official_account_order_count")
    private Integer officialAccountOrderCount;
    @JSONField(name = "official_account_first_day_order_count")
    private Integer officialAccountFirstDayOrderCount;
    @JSONField(name = "official_account_order_user_count")
    private Integer officialAccountOrderUserCount;
    @JSONField(name = "official_account_order_rate")
    private BigDecimal officialAccountOrderRate;
    @JSONField(name = "official_account_order_cost")
    private Integer officialAccountOrderCost;
    @JSONField(name = "official_account_order_amount")
    private Integer officialAccountOrderAmount;
    @JSONField(name = "official_account_first_day_order_amount")
    private Integer officialAccountFirstDayOrderAmount;
    @JSONField(name = "official_account_order_roi")
    private Integer officialAccountOrderRoi;
    @JSONField(name = "official_account_consult_count")
    private Integer officialAccountConsultCount;
    @JSONField(name = "official_account_reader_count")
    private Integer officialAccountReaderCount;
    @JSONField(name = "official_account_credit_apply_user_count")
    private Integer officialAccountCreditApplyUserCount;
    @JSONField(name = "official_account_credit_user_count")
    private Integer officialAccountCreditUserCount;
    @JSONField(name = "coupon_get_cost")
    private Integer couponGetCost;
    @JSONField(name = "coupon_get_rate")
    private BigDecimal couponGetRate;
    @JSONField(name = "coupon_use_count")
    private Integer couponUseCount;
    @JSONField(name = "forward_user_count")
    private Integer forwardUserCount;
    @JSONField(name = "video_outer_play_user_count")
    private Integer videoOuterPlayUserCount;
    @JSONField(name = "video_inner_play_user_count")
    private Integer videoInnerPlayUserCount;

}
